In [20]:
import pandas as pd

ratings = pd.read_csv('/home/supay/datos/rating.csv')
ratings = ratings[['user_id','anime_id','rating']]
movies = pd.read_csv('/home/supay/datos/anime.csv')
movies = movies[['anime_id','name']]

ratings = ratings.head(100000)
ratings = pd.merge(movies, ratings)

#dif = ratings.anime_id.unique()
#print(len(dif))

In [21]:
userRatings = ratings.pivot_table(index=['user_id'],columns=['anime_id'],values='rating')

In [22]:
corrMatrix = userRatings.corr()
corrMatrix.head()

anime_id,1,5,6,7,8,15,16,17,18,19,...,33522,33524,33558,33569,33618,33659,33934,33964,34103,34240
anime_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.755332,0.609533,0.977478,NaN,0.921639,0.729091,NaN,0.597763,0.730970,...,NaN,NaN,0.524042,NaN,NaN,NaN,NaN,NaN,0.781623,0.979546
5,0.755332,1.000000,0.471765,0.980482,NaN,0.500000,0.978997,NaN,1.000000,0.966754,...,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.983516
6,0.609533,0.471765,1.000000,0.539319,NaN,0.520184,0.940931,0.0,-0.353553,0.385031,...,NaN,1.0,0.500000,NaN,NaN,NaN,NaN,NaN,1.000000,0.544331
7,0.977478,0.980482,0.539319,1.000000,NaN,1.000000,0.995871,NaN,NaN,0.981981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
corrMatrix = userRatings.corr(method='pearson', min_periods=5)
corrMatrix.head(1167)

anime_id,1,5,6,7,8,15,16,17,18,19,...,33522,33524,33558,33569,33618,33659,33934,33964,34103,34240
anime_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.755332,0.609533,0.977478,NaN,0.921639,0.729091,NaN,0.597763,0.730970,...,NaN,NaN,0.524042,NaN,NaN,NaN,NaN,NaN,0.781623,0.979546
5,0.755332,1.000000,0.471765,NaN,NaN,NaN,0.978997,NaN,NaN,0.966754,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0.609533,0.471765,1.000000,0.539319,NaN,0.520184,0.940931,NaN,-0.353553,0.385031,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0.977478,NaN,0.539319,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1693,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1694,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1695,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1696,0.642411,NaN,0.717378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
anime = int(input("Introducir id del anime"))
calificacion = int(input("Introducir calificacion: "))

Introducir id del anime20
Introducir calificacion: 5

In [25]:
simCandidates = pd.Series()
#print(simCandidates)
# Recuperar las pelis similares a las calificadas
sims = corrMatrix[anime].dropna()
# Escalar la similaridad multiplicando por la calificaciÃ³n de la persona
sims = sims.map(lambda x: x * calificacion)
# AÃ±adir el puntaje a la lista de candidatos similares
simCandidates = simCandidates.append(sims)
    
#Mirar los resultados:
#print ("ordenando...")
#simCandidates.sort_values(inplace = True, ascending = False)
print (simCandidates.head(10))

1     3.380880
5     2.596128
6     3.462487
7     4.774920
15    3.549575
16    4.018329
18    3.143093
19    1.796698
20    5.000000
22    2.709116
dtype: float64

<ipython-input-25-ee604a7a5291>:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  simCandidates = pd.Series()

In [26]:
simCandidates = simCandidates.groupby(simCandidates.index).sum()

In [27]:
simCandidates.sort_values(inplace = True, ascending = False)
simCandidates.head(10)

20       5.000000
1365     5.000000
4550     4.999747
272      4.998748
10336    4.996412
1133     4.989311
6151     4.988477
5162     4.986998
6164     4.986039
11813    4.985491
dtype: float64

In [28]:
#print(myRatings)
filteredSims = simCandidates.drop(anime,errors='ignore')
filteredSims.head(10)

1365     5.000000
4550     4.999747
272      4.998748
10336    4.996412
1133     4.989311
6151     4.988477
5162     4.986998
6164     4.986039
11813    4.985491
3001     4.984686
dtype: float64